name: Example Workflow Dispatch

on:
  push:
  workflow_dispatch:
    inputs:
      project_environment:
        description: Which project environment to use
        required: true
        default: ghcr

jobs:
  example_job:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.project_environment || 'ghcr' }}
    steps:
      - name: Check if REGISTRY environment input exists
        run: |
          echo "Using registry input value: ${{ vars.REGISTRY }}"
      - name: Check if VAR1 environment input exists
        run: |
          echo "Using VAR1 input value: ${{ vars.VAR1 }}"
      - name: Check if VAR2 environment input exists
        run: |
          echo "Using VAR2 input value: ${{ vars.VAR2 }}"
      - name: Check if REGISTRY_PASSWORD secret input exists
        run: |
          echo "Using registry input value: ${{ secrets.REGISTRY_PASSWORD }}"
      - name: Add summary details
        if: always()
        run: |
          echo "## Summary Details" >> $GITHUB_STEP_SUMMARY
          echo "| Name | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| ---- | ----- |" >> $GITHUB_STEP_SUMMARY
          echo "| Pre-Merge Guild Deploy Image | registry.io/my_reponame/guild-deploy:COMMIT_HASH |" >> $GITHUB_STEP_SUMMARY
          echo "| Pre-Merge Guild Deploy Image ID | 186ef792f8dee9aa3aa21f05b4cb5a4c4cf91146 |" >> $GITHUB_STEP_SUMMARY
          echo "| Pre-Merge Cabal Build Image | registry.io/my_reponame/cabal:COMMIT_HASH |" >> $GITHUB_STEP_SUMMARY
          echo "| Pre-Merge Cabal Build Image ID | a21f05b4cb5a4c4cf91146186ef792f8dee9aa3a |" >> $GITHUB_STEP_SUMMARY
          echo "| G_ACCOUNT | Its_Me |" >> $GITHUB_STEP_SUMMARY
          echo "| BRANCH | my_branch |" >> $GITHUB_STEP_SUMMARY
          echo "| COMMIT | COMMIT_HASH |" >> $GITHUB_STEP_SUMMARY
          echo "| CARDANO_NODE_VERSION | 1.21 gigawats |" >> $GITHUB_STEP_SUMMARY
          echo "| GHC_VERSION | 4.1.5 |" >> $GITHUB_STEP_SUMMARY
