name: Test variables
on:
  workflow_dispatch:
jobs:
  test-repo-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Check if REPO_VARIABLE_1 and G_ACCOUNT are known before a checkout
        run: |
          echo "${REPO_VARIABLE_1} - ${G_ACCOUNT}"
      - name: Now checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check if REPO_VARIABLE_1 and G_ACCOUNT  is a known after a checkout
        run: |
          echo "${REPO_VARIABLE_1} - ${G_ACCOUNT}"
  test-created-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch release version from external repo
        run: |
          curl -sL https://raw.githubusercontent.com/trezor/data/master/bridge/latest.txt | grep tag_name | awk '{print $2}' | cut -d\" -f 2 > files/docker/node/release-versions/trezor-bridge-latest.txt
      - name: Create a variable named VERSION using environment file
        run: |
          echo "{VERSION}={$(cat ./files/docker/node/release-versions/trezor-bridge-latest.txt)} >> $GITHUB_ENV
      - name: Create a variable named VERSION2 using output file
        run: |
          echo "{VERSION2}={$(cat ./files/docker/node/release-versions/trezor-bridge-latest.txt)} >> $GITHUB_OUTPUT
      - name: Examine VERSION and VERSION2
        run: |
          echo -e "\n\tVariables \n\t\t- VERSION: ${VERSION} \n\t\t- VERSION2: ${VERSION2}"
  test-seperate-job-access-created-variables:
    runs-on: ubuntu-latest
    needs: test-created-variables
    steps:
      - name: Examine VERSION and VERSION2
        run: |
          echo -e "\n\tVariables \n\t\t- VERSION: ${VERSION} \n\t\t- VERSION2: ${VERSION2}"
