name: Test ENV from Inputs Workflow

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: Is the release a pre release?
        type: boolean
        required: false
        default: false
env:
  # those I'm sure they work
  image_path: 'spark-dev/deployment'
  # those not entirely sure but worth the shot.
  staging_archive: spark-offline-archive-${{ inputs.tag }}${{ inputs.prerelease == true && '-prerelease' || '' }}.run


jobs:
  setting-env-vars:
    runs-un: ubuntu-latest
    steps:
      - name: test access to staging_archive env var
        run: |
          echo ${{ env.staging_archive }}
