name: Test Tee Into $GITHUB files

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to be released
        required: true
      prerelease:
        description: Is the release a pre release?
        type: boolean
        required: false
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Create one ENV variable and access it immediately
        run: |
          echo "myvalue=some.string.of.text" | tee -a $GITHUB_OUTPUT >> $GITHUB_ENV
          echo "myvalue2=some.other.string.of.text" | tee -a $GITHUB_ENV >> $GITHUB_OUTPUT
          echo access the variable immediately: ${{ env.myvalue }}
      - name: Access the ENV variable from the prior step
        run: |
          echo access the variable later: ${{ env.myvalue }}
          echo access the teed variable later: ${{ env.myvalue2 }}
      - name: Execute if not prerelease
        run: |
          echo "GA, not a prerelease"
        if: ${{ ! inputs.prerelease }}
      - name: Execute if a prerelease
        run: |
          echo "Prerelease, not a GA"
        if: ${{ inputs.prerelease }}
