name: Example Workflow Dispatch

on:
  push:
  workflow_dispatch:
    inputs:
      project_environment:
        description: Which project environment to use
        required: true
        default: ghcr

jobs:
  example_job:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.project_environment || 'ghcr' }}
    steps:
      - name: Check name of the job environment that is loaded
        run: |
          echo "job environment: ${{ env.GITHUB_ENVIRONMENT }}"
      - name: Check if REGISTRY environment input exists
        run: |
          echo "Using registry input value: ${{ vars.REGISTRY }}"
      - name: Check if VAR1 environment input exists
        run: |
          echo "Using VAR1 input value: ${{ vars.VAR1 }}"
      - name: Check if VAR2 environment input exists
        run: |
          echo "Using VAR2 input value: ${{ vars.VAR2 }}"
      - name: Check if REGISTRY_USER secret input exists
        run: |
          echo "Using registry input value: ${{ secrets.REGISTRY_PASSWORD }}"
