name: Test variables
on:
  workflow_dispatch:
env:
  # Setting an environment variable with the value of a configuration variable
  G_ACCOUNT: ${{ vars.G_ACCOUNT }}
jobs:
  test-gh-workflow-variables:
    steps:
      - name: Check repository owner as environment variable
        run: |
          echo "Owner: ${GITHUB_REPOSITORY_OWNER}"
      - name: Check repository owner as environment jinja tag
        run: |
          echo "Owner: ${{ env.GITHUB_REPOSITORY_OWNER }}"
  test-repo-variables:
    env:
      JOB_VAR: ${{ vars.G_ACCOUNT }}
    runs-on: ubuntu-latest
    steps:
      - name: Check if REPO_VARIABLE_1 and G_ACCOUNT are known before a checkout inside vars context
        run: |
          echo -e "Variables: \n\t- Repo var 1: ${{ vars.REPO_VARIABLE_1 }} \n\t- G account: ${{ vars.G_ACCOUNT }}"
      - name: Now checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check if REPO_VARIABLE_1 and G_ACCOUNT  is a known after a checkout
        run: |
          echo -e "Variables: \n\t- Repo var 1: ${{ vars.REPO_VARIABLE_1 }} \n\t- G account: ${{ vars.G_ACCOUNT }}"
      - name: Check that JOB_VAR variable is available inside the job
        run: |
          echo -e "Variables: \n\t- JOB_VAR: ${JOB_VAR}"
      - name: Check that STEP_VAR variable is available
        env:
          STEP_VAR:  ${{ vars.G_ACCOUNT }}
        run: |
          echo -e "Variables: \n\t- STEP_VAR: ${STEP_VAR}"
          
  test-created-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Create a file as an example source for variable
        run: |
          echo "1.0.7" > ./version.txt
      - name: Create a variable named VERSION using environment file
        run: |
          echo -e "VERSION=1.99.20" >> $GITHUB_ENV
      - name: Create a variable named VERSION2 using output file
        id: my-github-output-variable
        run: |
          echo -e "VERSION=2.44.21" >> $GITHUB_OUTPUT
      - name: Examine VERSION and VERSION2
        env:
          VERSION: ${{ env.VERSION }}
          VERSION2: ${{ steps.my-github-output-variable.outputs.VERSION }}
        run: |
          echo -e "Variables \n\t- VERSION: ${VERSION} \n\t- VERSION2: ${VERSION2}"
  test-seperate-job-access-created-variables:
    runs-on: ubuntu-latest
    needs: test-created-variables
    env:
      VERSION:  ${{ needs.test-created-variables.env.VERSION }}
      VERSION2: ${{ needs.test-created-variables.outputs.VERSION }}
    steps:
      - name: Examine VERSION and VERSION2 as jinja variables
        run: |
          echo -e "Variables \n\t- VERSION: ${VERSION} \n\t- VERSION2: ${VERSION2}"
