name: Example Workflow Dispatch

on:
  push:
  workflow_dispatch:
    inputs:
      registry:
        description: Docker registry to use
        required: false
        default: 'ghcr.io'

jobs:
  example_job:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ${{ github.event.inputs.registry || 'ghcr.io' }}
    steps:
      - name: Check if registry input exists
        run: |
          echo "Using registry input value: ${{ env.REGISTRY }}"
